apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nature-node.yaml
  - nature-cluster.yaml
  - nature-storage.yaml
  - nature-hardware.yaml
  - remote-write-recording.yaml
