apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - servicemonitor-ceph.yaml
  - ingress-prometheus.yaml
  - ingress-alertmanager.yaml
  - node-problem-detector
  - rules
