apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
  - image-automation.yaml
images:
  - name: hedche/peanut
    newName: hedche/peanut # {"$imagepolicy": "flux-system:peanut:name"}
    newTag: main-95584c3-1785450298 # {"$imagepolicy": "flux-system:peanut:tag"}
