apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peanut-memory-ceph
  namespace: peanut
  labels:
    app.kubernetes.io/name: peanut
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
