apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - sonarr
  - radarr
  - prowlarr
  - flaresolverr
  - decluttarr
  - image-automation.yaml
images:
  - name: lscr.io/linuxserver/sonarr
    newTag: 4.0.19.2979-ls322 # {"$imagepolicy": "flux-system:sonarr:tag"}
  - name: lscr.io/linuxserver/radarr
    newTag: 6.3.0.10514-ls314 # {"$imagepolicy": "flux-system:radarr:tag"}
  - name: lscr.io/linuxserver/prowlarr
    newTag: 2.5.2.5491-ls156 # {"$imagepolicy": "flux-system:prowlarr:tag"}
  - name: ghcr.io/flaresolverr/flaresolverr
    newTag: v3.5.0 # {"$imagepolicy": "flux-system:flaresolverr:tag"}
  - name: ghcr.io/manimatter/decluttarr
    newTag: v2.1.0 # {"$imagepolicy": "flux-system:decluttarr:tag"}
