apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-rules
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/monitoring-rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: monitoring # PrometheusRule/ServiceMonitor/PodMonitor CRDs
